CREATE DATABASE IF NOT EXISTS BD_EST_SUPER;
USE BD_EST_SUPER;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR (100) NOT NULL,
	TIPO VARCHAR (100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	CODIGO_BARRAS VARCHAR (20) PRIMARY KEY NOT NULL,
    NOME VARCHAR (100) NOT NULL,
    PRECO DOUBLE NOT NULL,
    PESO DOUBLE
);

CREATE TABLE IF NOT  EXISTS FORNECEDOR(
	CNPJ VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO_FORNECEDOR(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_PRODUTO_CODIGO_BARRAS  VARCHAR(20),
    FK_FORNECEDOR_CNPJ VARCHAR (14),
	FOREIGN KEY (FK_PRODUTO_CODIGO_BARRAS) REFERENCES PRODUTO(CODIGO_BARRAS),
    FOREIGN KEY (FK_FORNECEDOR_CNPJ) REFERENCES FORNECEDOR(CNPJ)
);