CREATE DATABASE IF NOT EXISTS BD_MUSICA;
USE BD_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR (100) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DURACAO TIMESTAMP 
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    LETRA VARCHAR(100),
    DURACAO TIMESTAMP,
    FK_ALBUM_ID INT,
    FOREIGN KEY (FK_ALBUM_ID) REFERENCES ALBUM(ID),
    FK_GENERO_ID INT,
    FOREIGN KEY (FK_GENERO_ID) REFERENCES GENERO(ID)
);
